force-app/main/default/objects/Cart__c/Cart__c.object-meta.xml
<CustomObject>
    <label>Cart</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Cart Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CartItem__c/CartItem__c.object-meta.xml
<CustomObject>
    <label>Cart Item</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Cart Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cart Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CartItem__c/fields/Cart__c.field-meta.xml
<CustomField>
    <fullName>Cart__c</fullName>
    <label>Cart</label>
    <referenceTo>Cart__c</referenceTo>
    <relationshipLabel>Cart Items</relationshipLabel>
    <relationshipName>CartItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CartItem__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CartItem__c/fields/PricePerEach__c.field-meta.xml
<CustomField>
    <fullName>PricePerEach__c</fullName>
    <label>Price per Each</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CartItem__c/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <label>Product Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CartItem__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
public inherited sharing class TestDataFactory {
    public static User createTestUser(String userLastName, String profileName, List<String> permisionSetNames) {
        Profile profile = [SELECT Id FROM Profile WHERE Name = :profileName LIMIT 1];
        List<PermissionSet> permissionSets = [SELECT Id FROM PermissionSet WHERE Name IN :permisionSetNames];

        User user = new user();
        user.LastName = userLastName;
        user.Email = userLastName + '@' + userLastName + '.com';
        user.Alias = RandomDataGenerator.generateRandomString(8);
        user.Username = userLastName + '@' + userLastName + '.com';
        user.LocaleSidKey = 'en_US';
        user.TimeZoneSidKey = 'GMT';
        user.ProfileId = profile.Id;
        user.LanguageLocaleKey = 'en_US';
        user.EmailEncodingKey = 'UTF-8';
        insert user;

        List<PermissionSetAssignment> permissionSetAssignments = new List<PermissionSetAssignment>();
        for (PermissionSet permissionSet : permissionSets) {
            permissionSetAssignments.add(new PermissionSetAssignment(PermissionSetId = permissionSet.Id, AssigneeId = user.Id));
        }
        System.runAs(user) {
            insert permissionSetAssignments;
        }

        return user;
    }

    public static List<Cart__c> createCarts(Integer size) {
        List<Cart__c> carts = new List<Cart__c>();

        for (Integer i = 0; i < size; i++) {
            carts.add(new Cart__c());
        }

        return carts;
    }

    public static List<CartItem__c> createCartItems(Cart__c cart, Integer size) {
        List<CartItem__c> cartItems = new List<CartItem__c>();

        for (Integer i = 0; i < size; i++) {
            cartItems.add(new CartItem__c(
                Cart__c = cart.Id,
                ExternalId__c = RandomDataGenerator.generateRandomString(18),
                ProductName__c = RandomDataGenerator.generateRandomString(10),
                PricePerEach__c = RandomDataGenerator.generateRandomNumber(5) / 100,
                Quantity__c = RandomDataGenerator.generateRandomNumber(5)
            ));
        }

        return cartItems;
    }
}